FROM node:20-alpine AS builder

WORKDIR /app

# Installation globale de l'Angular CLI et des outils de développement
RUN npm install -g @angular/cli@19 eslint prettier

# Installation des dépendances de développement
RUN npm install -D tailwindcss postcss autoprefixer && \
  npm install -D cypress @cypress/schematic

# Initialisation de Tailwind (on le fera plutôt dans la commande du docker-compose)
# RUN npx tailwindcss init

EXPOSE 4200