<?php

return [
    'auto_migrate' => true,
    'schema' => [
        'users' => [
            'uuid' => 'uuid:primary',
            'firstname' => 'string:required',  
            'lastname' => 'string:required',
            'email' => 'string:required:unique',
            'email_verified' => 'boolean:default(false)',
            'password' => 'string:required',
            'birthdate' => 'date:required',
            'phone' => 'string:required',
            'token' => 'string:required',
            'address' => 'string:required', 
            'address_complement' => 'string:nullable',
            'zipcode' => 'string:required',
            'city' => 'string:required',
            'country' => 'string:required',
            'role_id' => 'foreignId:required',
            'timestamps' => true,
            'softDeletes' => true,
        ],
        'user_patients' => [
            'uuid' => 'uuid:primary',
            'gender' => 'string:required',
            'is_anonymous' => 'boolean:default(false)',
            'timestamps' => true,
        ],
        'user_professionals' => [
            'uuid' => 'uuid:primary', 
            'languages' => 'json:required',
            'experience' => 'integer:required',
            'certification' => 'string:required',
            'company_name' => 'string:required',
            'medical_identification_number' => 'string:required:unique',
            'company_identification_number' => 'string:required:unique',
            'timestamps' => true,
        ],
        'professional_therapy_domain' => [
            'professional_uuid' => 'uuid:foreign',
            'therapy_domain_id' => 'foreignId',
            'timestamps' => false,
        ],
        'roles' => [
            'id' => 'id',
            'name' => 'string:required:unique',
            'timestamps' => false,
        ],
        'therapy_domains' => [
            'id' => 'id',
            'name' => 'string:required:unique',
            'description' => 'string:nullable',
            'is_active' => 'boolean:default(true)',
            'created_at' => 'timestamp:required',
            'updated_at' => 'timestamp:nullable',
            'timestamps' => true,
        ],
        'notifications' => [
            'id' => 'id',
            'user_type' => 'string:required',
            'value' => 'string:required',
            'user_uuid' => 'uuid:foreign:users,uuid',
            'created_at' => 'timestamp:required',
            'deleted_at' => 'timestamp:nullable',
            'timestamps' => false,
        ],
    ],
];